### PR TITLE
Add {N} angular support

### PR DESCRIPTION
**Pull request by legion151**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the new behavior?
Adds nativescript angular support based on
https://docs.nativescript.org/angular/plugins/angular-plugin

### CODE REVIEW

**Comment by legion151** [comment]
honestly idk how to fix the build - it works for me on android and ios

**Comment by legion151** [comment]
well i guess i learned it ;)

**Comment by legion151** [comment]
is this project dead? or is there a problem?

**Comment by flore2003** [comment]
I will review this asap and get it merged. Sorry for the delay

**Pull request merged**
